server:
  servlet:
    context-path: /api
  port: 9966

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    format-sql: true
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false


logging:
  level:
    org.springframework: ERROR
    com.spring.batch.service: DEBUG