server:
  servlet:
    context-path: /api/v1/jwt
  port: 9898

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt-security?useSSL=false
    username: root
    password: pass@word1
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

