server:
  servlet:
    context-path: /api/v1/digitalbooks
  port: 9977

spring:
  datasource:
    url: jdbc:mysql://userdigitalbookstore.chfcawofc3aj.ap-northeast-1.rds.amazonaws.com:3306/digitalbooks
    username: root
    password: password
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  resources:
    static-locations: classpath:/webapp/