server:
  servlet:
    context-path: /api/vrk/tms
  port: 9966

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    resources:
      static-locations: classpath:/webapp/

logging:
  level:
    org.springframework: ERROR
    com.vrk.tms.service: DEBUG