spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vrk-bank?useSSL=false
    username: root
    password: pass@word1
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: create
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        web: ERROR
    com: DEBUG
