spring:
  datasource:
    url: jdbc:mysql://vrk-bank-management-db.chfcawofc3aj.ap-northeast-1.rds.amazonaws.com:3306/vrkbankdb
    username: root
    password: password
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        web: ERROR
    com: INFO
