server:
  servlet:
    context-path: /api/v1/digitalbooks/author
  port: 9966

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital-books?useSSL=false
    username: root
    password: pass@word1
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: create
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


