server:
  servlet:
    context-path: /library
  port: 9966

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-management?useSSL=false
    username: root
    password: pass@word1
  jpa:
    hibernate:
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  resources:
    static-locations: classpath:/webapp/